=begin
#Payer Analytics - Healthcare Intelligence API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

require 'date'
require 'time'

module SmrfClient
  class BillingCodeType
    CPT = "CPT".freeze
    HCPCS = "HCPCS".freeze
    ICD = "ICD".freeze
    MS_DRG = "MS-DRG".freeze
    R_DRG = "R-DRG".freeze
    S_DRG = "S-DRG".freeze
    APS_DRG = "APS-DRG".freeze
    AP_DRG = "AP-DRG".freeze
    APR_DRG = "APR-DRG".freeze
    APC = "APC".freeze
    NDC = "NDC".freeze
    HIPPS = "HIPPS".freeze
    LOCAL = "LOCAL".freeze
    EAPG = "EAPG".freeze
    CDT = "CDT".freeze
    RC = "RC".freeze
    CSTM_ALL = "CSTM-ALL".freeze

    def self.all_vars
      @all_vars ||= [CPT, HCPCS, ICD, MS_DRG, R_DRG, S_DRG, APS_DRG, AP_DRG, APR_DRG, APC, NDC, HIPPS, LOCAL, EAPG, CDT, RC, CSTM_ALL].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if BillingCodeType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #BillingCodeType"
    end
  end
end
