=begin
#Payer Analytics - Healthcare Intelligence API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

require 'date'
require 'time'

module SmrfClient
  class PlaceOfServiceCode
    N01 = "01".freeze
    N02 = "02".freeze
    N03 = "03".freeze
    N04 = "04".freeze
    N05 = "05".freeze
    N06 = "06".freeze
    N07 = "07".freeze
    N08 = "08".freeze
    N09 = "09".freeze
    N10 = "10".freeze
    N11 = "11".freeze
    N12 = "12".freeze
    N13 = "13".freeze
    N14 = "14".freeze
    N15 = "15".freeze
    N16 = "16".freeze
    N17 = "17".freeze
    N18 = "18".freeze
    N19 = "19".freeze
    N20 = "20".freeze
    N21 = "21".freeze
    N22 = "22".freeze
    N23 = "23".freeze
    N24 = "24".freeze
    N25 = "25".freeze
    N26 = "26".freeze
    N27 = "27".freeze
    N28 = "28".freeze
    N29 = "29".freeze
    N30 = "30".freeze
    N31 = "31".freeze
    N32 = "32".freeze
    N33 = "33".freeze
    N34 = "34".freeze
    N35 = "35".freeze
    N36 = "36".freeze
    N37 = "37".freeze
    N38 = "38".freeze
    N39 = "39".freeze
    N40 = "40".freeze
    N41 = "41".freeze
    N42 = "42".freeze
    N43 = "43".freeze
    N44 = "44".freeze
    N45 = "45".freeze
    N46 = "46".freeze
    N47 = "47".freeze
    N48 = "48".freeze
    N49 = "49".freeze
    N50 = "50".freeze
    N51 = "51".freeze
    N52 = "52".freeze
    N53 = "53".freeze
    N54 = "54".freeze
    N55 = "55".freeze
    N56 = "56".freeze
    N57 = "57".freeze
    N58 = "58".freeze
    N59 = "59".freeze
    N60 = "60".freeze
    N61 = "61".freeze
    N62 = "62".freeze
    N63 = "63".freeze
    N64 = "64".freeze
    N65 = "65".freeze
    N66 = "66".freeze
    N67 = "67".freeze
    N68 = "68".freeze
    N69 = "69".freeze
    N70 = "70".freeze
    N71 = "71".freeze
    N72 = "72".freeze
    N73 = "73".freeze
    N74 = "74".freeze
    N75 = "75".freeze
    N76 = "76".freeze
    N77 = "77".freeze
    N78 = "78".freeze
    N79 = "79".freeze
    N80 = "80".freeze
    N81 = "81".freeze
    N82 = "82".freeze
    N83 = "83".freeze
    N84 = "84".freeze
    N85 = "85".freeze
    N86 = "86".freeze
    N87 = "87".freeze
    N88 = "88".freeze
    N89 = "89".freeze
    N90 = "90".freeze
    N91 = "91".freeze
    N92 = "92".freeze
    N93 = "93".freeze
    N94 = "94".freeze
    N95 = "95".freeze
    N96 = "96".freeze
    N97 = "97".freeze
    N98 = "98".freeze
    N99 = "99".freeze

    def self.all_vars
      @all_vars ||= [N01, N02, N03, N04, N05, N06, N07, N08, N09, N10, N11, N12, N13, N14, N15, N16, N17, N18, N19, N20, N21, N22, N23, N24, N25, N26, N27, N28, N29, N30, N31, N32, N33, N34, N35, N36, N37, N38, N39, N40, N41, N42, N43, N44, N45, N46, N47, N48, N49, N50, N51, N52, N53, N54, N55, N56, N57, N58, N59, N60, N61, N62, N63, N64, N65, N66, N67, N68, N69, N70, N71, N72, N73, N74, N75, N76, N77, N78, N79, N80, N81, N82, N83, N84, N85, N86, N87, N88, N89, N90, N91, N92, N93, N94, N95, N96, N97, N98, N99].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if PlaceOfServiceCode.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #PlaceOfServiceCode"
    end
  end
end
