=begin
#Payer Analytics - Healthcare Intelligence API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SmrfClient::BillingCodeApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BillingCodeApi' do
  before do
    # run before each test
    @api_instance = SmrfClient::BillingCodeApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BillingCodeApi' do
    it 'should create an instance of BillingCodeApi' do
      expect(@api_instance).to be_instance_of(SmrfClient::BillingCodeApi)
    end
  end

  # unit tests for billing_codes_get
  # Returns all billing codes
  # @param [Hash] opts the optional parameters
  # @return [Array<BillingCodesGet200ResponseInner>]
  describe 'billing_codes_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for billing_codes_search_get
  # Returns billing codes for required parameters
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :rate_source_id The id of the rate source to query against
  # @option opts [Integer] :reporting_plan_ids The ids of reporting plans to query against
  # @return [Array<BillingCodeAndType>]
  describe 'billing_codes_search_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
