=begin
#Payer Analytics - Healthcare Intelligence API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SmrfClient::PlaceOfServiceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PlaceOfServiceApi' do
  before do
    # run before each test
    @api_instance = SmrfClient::PlaceOfServiceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PlaceOfServiceApi' do
    it 'should create an instance of PlaceOfServiceApi' do
      expect(@api_instance).to be_instance_of(SmrfClient::PlaceOfServiceApi)
    end
  end

  # unit tests for places_of_service_get
  # Returns all places of service
  # @param [Hash] opts the optional parameters
  # @return [Array<PlaceOfService>]
  describe 'places_of_service_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
