=begin
#Payer Analytics - Healthcare Intelligence API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SmrfClient::RateSourceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RateSourceApi' do
  before do
    # run before each test
    @api_instance = SmrfClient::RateSourceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RateSourceApi' do
    it 'should create an instance of RateSourceApi' do
      expect(@api_instance).to be_instance_of(SmrfClient::RateSourceApi)
    end
  end

  # unit tests for rate_sources_get
  # Returns all rate sources
  # @param [Hash] opts the optional parameters
  # @return [Array<RateSource>]
  describe 'rate_sources_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
