=begin
#Payer Analytics - Healthcare Intelligence API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SmrfClient::ReportingPlanApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ReportingPlanApi' do
  before do
    # run before each test
    @api_instance = SmrfClient::ReportingPlanApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReportingPlanApi' do
    it 'should create an instance of ReportingPlanApi' do
      expect(@api_instance).to be_instance_of(SmrfClient::ReportingPlanApi)
    end
  end

  # unit tests for rate_sources_rate_source_id_reporting_plans_get
  # Returns all reporting plans for rate source
  # @param rate_source_id ID of rate source that needs to be fetched
  # @param [Hash] opts the optional parameters
  # @return [Array<ReportingPlan>]
  describe 'rate_sources_rate_source_id_reporting_plans_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
