=begin
#Payer Analytics - Healthcare Intelligence API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SmrfClient::CountiesObject
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SmrfClient::CountiesObject do
  let(:instance) { SmrfClient::CountiesObject.new }

  describe 'test an instance of CountiesObject' do
    it 'should create an instance of CountiesObject' do
      expect(instance).to be_instance_of(SmrfClient::CountiesObject)
    end
  end
  describe 'test attribute "counties"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
