=begin
#Payer Analytics - Healthcare Intelligence API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SmrfClient::UniqueValuesFieldOptionsObject
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SmrfClient::UniqueValuesFieldOptionsObject do
  let(:instance) { SmrfClient::UniqueValuesFieldOptionsObject.new }

  describe 'test an instance of UniqueValuesFieldOptionsObject' do
    it 'should create an instance of UniqueValuesFieldOptionsObject' do
      expect(instance).to be_instance_of(SmrfClient::UniqueValuesFieldOptionsObject)
    end
  end
  describe 'test attribute "field"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["applicable_specialties", "npi", "npi_specialties", "tin_value", "provider_name"])
      # validator.allowable_values.each do |value|
      #   expect { instance.field = value }.not_to raise_error
      # end
    end
  end

end
